// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package main

import (
	"context"
	"fmt"
	"math"

	"github.com/golang/protobuf/proto"
	"google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FizzBuzzRequest struct {
	Input                int32    `protobuf:"varint,1,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FizzBuzzRequest) Reset()         { *m = FizzBuzzRequest{} }
func (m *FizzBuzzRequest) String() string { return proto.CompactTextString(m) }
func (*FizzBuzzRequest) ProtoMessage()    {}
func (*FizzBuzzRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *FizzBuzzRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FizzBuzzRequest.Unmarshal(m, b)
}
func (m *FizzBuzzRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FizzBuzzRequest.Marshal(b, m, deterministic)
}
func (m *FizzBuzzRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FizzBuzzRequest.Merge(m, src)
}
func (m *FizzBuzzRequest) XXX_Size() int {
	return xxx_messageInfo_FizzBuzzRequest.Size(m)
}
func (m *FizzBuzzRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FizzBuzzRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FizzBuzzRequest proto.InternalMessageInfo

func (m *FizzBuzzRequest) GetInput() int32 {
	if m != nil {
		return m.Input
	}
	return 0
}

type FizzBuzzResponse struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FizzBuzzResponse) Reset()         { *m = FizzBuzzResponse{} }
func (m *FizzBuzzResponse) String() string { return proto.CompactTextString(m) }
func (*FizzBuzzResponse) ProtoMessage()    {}
func (*FizzBuzzResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *FizzBuzzResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FizzBuzzResponse.Unmarshal(m, b)
}
func (m *FizzBuzzResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FizzBuzzResponse.Marshal(b, m, deterministic)
}
func (m *FizzBuzzResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FizzBuzzResponse.Merge(m, src)
}
func (m *FizzBuzzResponse) XXX_Size() int {
	return xxx_messageInfo_FizzBuzzResponse.Size(m)
}
func (m *FizzBuzzResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FizzBuzzResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FizzBuzzResponse proto.InternalMessageInfo

func (m *FizzBuzzResponse) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type StatsRequest struct {
	Values               []int32  `protobuf:"varint,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsRequest) Reset()         { *m = StatsRequest{} }
func (m *StatsRequest) String() string { return proto.CompactTextString(m) }
func (*StatsRequest) ProtoMessage()    {}
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *StatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsRequest.Unmarshal(m, b)
}
func (m *StatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsRequest.Marshal(b, m, deterministic)
}
func (m *StatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsRequest.Merge(m, src)
}
func (m *StatsRequest) XXX_Size() int {
	return xxx_messageInfo_StatsRequest.Size(m)
}
func (m *StatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatsRequest proto.InternalMessageInfo

func (m *StatsRequest) GetValues() []int32 {
	if m != nil {
		return m.Values
	}
	return nil
}

type StatsResponse struct {
	Min                  int32    `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int32    `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Median               float64  `protobuf:"fixed64,3,opt,name=median,proto3" json:"median,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsResponse) Reset()         { *m = StatsResponse{} }
func (m *StatsResponse) String() string { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()    {}
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *StatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsResponse.Unmarshal(m, b)
}
func (m *StatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsResponse.Marshal(b, m, deterministic)
}
func (m *StatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsResponse.Merge(m, src)
}
func (m *StatsResponse) XXX_Size() int {
	return xxx_messageInfo_StatsResponse.Size(m)
}
func (m *StatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatsResponse proto.InternalMessageInfo

func (m *StatsResponse) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *StatsResponse) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *StatsResponse) GetMedian() float64 {
	if m != nil {
		return m.Median
	}
	return 0
}

type CodeInput struct {
	Input                string   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeInput) Reset()         { *m = CodeInput{} }
func (m *CodeInput) String() string { return proto.CompactTextString(m) }
func (*CodeInput) ProtoMessage()    {}
func (*CodeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *CodeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeInput.Unmarshal(m, b)
}
func (m *CodeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeInput.Marshal(b, m, deterministic)
}
func (m *CodeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeInput.Merge(m, src)
}
func (m *CodeInput) XXX_Size() int {
	return xxx_messageInfo_CodeInput.Size(m)
}
func (m *CodeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeInput.DiscardUnknown(m)
}

var xxx_messageInfo_CodeInput proto.InternalMessageInfo

func (m *CodeInput) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type CodeOutput struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeOutput) Reset()         { *m = CodeOutput{} }
func (m *CodeOutput) String() string { return proto.CompactTextString(m) }
func (*CodeOutput) ProtoMessage()    {}
func (*CodeOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *CodeOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeOutput.Unmarshal(m, b)
}
func (m *CodeOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeOutput.Marshal(b, m, deterministic)
}
func (m *CodeOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeOutput.Merge(m, src)
}
func (m *CodeOutput) XXX_Size() int {
	return xxx_messageInfo_CodeOutput.Size(m)
}
func (m *CodeOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CodeOutput proto.InternalMessageInfo

func (m *CodeOutput) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type JosephusInput struct {
	N                    int32    `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	K                    int32    `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JosephusInput) Reset()         { *m = JosephusInput{} }
func (m *JosephusInput) String() string { return proto.CompactTextString(m) }
func (*JosephusInput) ProtoMessage()    {}
func (*JosephusInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *JosephusInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JosephusInput.Unmarshal(m, b)
}
func (m *JosephusInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JosephusInput.Marshal(b, m, deterministic)
}
func (m *JosephusInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JosephusInput.Merge(m, src)
}
func (m *JosephusInput) XXX_Size() int {
	return xxx_messageInfo_JosephusInput.Size(m)
}
func (m *JosephusInput) XXX_DiscardUnknown() {
	xxx_messageInfo_JosephusInput.DiscardUnknown(m)
}

var xxx_messageInfo_JosephusInput proto.InternalMessageInfo

func (m *JosephusInput) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

func (m *JosephusInput) GetK() int32 {
	if m != nil {
		return m.K
	}
	return 0
}

type JosephusOutput struct {
	S                    int32    `protobuf:"varint,1,opt,name=s,proto3" json:"s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JosephusOutput) Reset()         { *m = JosephusOutput{} }
func (m *JosephusOutput) String() string { return proto.CompactTextString(m) }
func (*JosephusOutput) ProtoMessage()    {}
func (*JosephusOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *JosephusOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JosephusOutput.Unmarshal(m, b)
}
func (m *JosephusOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JosephusOutput.Marshal(b, m, deterministic)
}
func (m *JosephusOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JosephusOutput.Merge(m, src)
}
func (m *JosephusOutput) XXX_Size() int {
	return xxx_messageInfo_JosephusOutput.Size(m)
}
func (m *JosephusOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_JosephusOutput.DiscardUnknown(m)
}

var xxx_messageInfo_JosephusOutput proto.InternalMessageInfo

func (m *JosephusOutput) GetS() int32 {
	if m != nil {
		return m.S
	}
	return 0
}

func init() {
	proto.RegisterType((*FizzBuzzRequest)(nil), "play.FizzBuzzRequest")
	proto.RegisterType((*FizzBuzzResponse)(nil), "play.FizzBuzzResponse")
	proto.RegisterType((*StatsRequest)(nil), "play.StatsRequest")
	proto.RegisterType((*StatsResponse)(nil), "play.StatsResponse")
	proto.RegisterType((*CodeInput)(nil), "play.CodeInput")
	proto.RegisterType((*CodeOutput)(nil), "play.CodeOutput")
	proto.RegisterType((*JosephusInput)(nil), "play.JosephusInput")
	proto.RegisterType((*JosephusOutput)(nil), "play.JosephusOutput")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xc1, 0x4e, 0xc2, 0x40,
	0x14, 0x64, 0xc5, 0x36, 0xf0, 0x04, 0x21, 0x2b, 0x92, 0xa6, 0x07, 0x83, 0x1b, 0xa3, 0x44, 0x0d,
	0x07, 0x3c, 0x78, 0xf0, 0x86, 0x89, 0x89, 0x1a, 0xa3, 0xa9, 0x37, 0x6f, 0xab, 0x6c, 0xb4, 0xa1,
	0x74, 0x6b, 0x5f, 0x97, 0x40, 0xff, 0xd7, 0xff, 0x30, 0xed, 0xee, 0x82, 0x25, 0xf1, 0xd6, 0x99,
	0xce, 0x9b, 0xce, 0x9b, 0x3e, 0x68, 0xa3, 0x48, 0x17, 0xe1, 0x87, 0x18, 0x25, 0xa9, 0xcc, 0x24,
	0xdd, 0x4d, 0x22, 0xbe, 0x62, 0x67, 0xd0, 0xb9, 0x0b, 0xf3, 0x7c, 0xa2, 0xf2, 0x3c, 0x10, 0xdf,
	0x4a, 0x60, 0x46, 0x7b, 0xe0, 0x84, 0x71, 0xa2, 0x32, 0x8f, 0x0c, 0xc8, 0xd0, 0x09, 0x34, 0x60,
	0xe7, 0xd0, 0xdd, 0x08, 0x31, 0x91, 0x31, 0x0a, 0xda, 0x07, 0x57, 0xaa, 0xcc, 0x4a, 0x9b, 0x81,
	0x41, 0xec, 0x14, 0x5a, 0xaf, 0x19, 0xcf, 0xd0, 0x3a, 0xf6, 0xc1, 0x5d, 0xf0, 0x48, 0x09, 0xf4,
	0xc8, 0xa0, 0x3e, 0x74, 0x02, 0x83, 0xd8, 0x23, 0xb4, 0x8d, 0xce, 0x18, 0x76, 0xa1, 0x3e, 0x0f,
	0x63, 0xf3, 0xe1, 0xe2, 0xb1, 0x64, 0xf8, 0xd2, 0xdb, 0x31, 0x0c, 0x5f, 0x16, 0x66, 0x73, 0x31,
	0x0d, 0x79, 0xec, 0xd5, 0x07, 0x64, 0x48, 0x02, 0x83, 0xd8, 0x31, 0x34, 0x6f, 0xe5, 0x54, 0xdc,
	0x17, 0x69, 0xab, 0x3b, 0x34, 0xed, 0x0e, 0x27, 0x00, 0x85, 0xe4, 0xb9, 0x4c, 0xf9, 0x6f, 0xfa,
	0x0b, 0x68, 0x3f, 0x48, 0x14, 0xc9, 0x97, 0x42, 0x6d, 0xd6, 0x02, 0x62, 0x33, 0x91, 0xb8, 0x40,
	0x33, 0x93, 0x87, 0xcc, 0xd8, 0x11, 0xec, 0x5b, 0xb1, 0xb1, 0x6d, 0x01, 0x41, 0xab, 0xc6, 0xf1,
	0x0f, 0x81, 0xbd, 0x97, 0x88, 0xaf, 0x3e, 0x53, 0xa9, 0xe2, 0x29, 0xd2, 0x1b, 0x68, 0xd8, 0x1a,
	0xe9, 0xe1, 0xa8, 0xf8, 0x05, 0xa3, 0xad, 0xfe, 0xfd, 0xfe, 0x36, 0xad, 0xcb, 0x61, 0x35, 0x3a,
	0x06, 0xa7, 0xec, 0x8b, 0x52, 0x2d, 0xf9, 0x5b, 0xb2, 0x7f, 0x50, 0xe1, 0xd6, 0x33, 0x97, 0xe0,
	0x3c, 0xc9, 0x14, 0x05, 0xed, 0xe8, 0xf7, 0xeb, 0x8e, 0xfc, 0xee, 0x86, 0xd0, 0xd1, 0x59, 0x8d,
	0x5e, 0x43, 0xc3, 0xae, 0x43, 0x8d, 0x61, 0xa5, 0x0b, 0xbf, 0x57, 0x25, 0xed, 0xe0, 0xc4, 0x7d,
	0x2b, 0xef, 0xe9, 0xdd, 0x2d, 0x8f, 0xeb, 0xea, 0x37, 0x00, 0x00, 0xff, 0xff, 0x11, 0x3b, 0x14,
	0x3a, 0x6d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlaygroundsClient is the client API for Playgrounds service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlaygroundsClient interface {
	FizzBuzz(ctx context.Context, in *FizzBuzzRequest, opts ...grpc.CallOption) (*FizzBuzzResponse, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	Morse(ctx context.Context, in *CodeInput, opts ...grpc.CallOption) (*CodeOutput, error)
	Josephus(ctx context.Context, in *JosephusInput, opts ...grpc.CallOption) (*JosephusOutput, error)
}

type playgroundsClient struct {
	cc *grpc.ClientConn
}

func NewPlaygroundsClient(cc *grpc.ClientConn) PlaygroundsClient {
	return &playgroundsClient{cc}
}

func (c *playgroundsClient) FizzBuzz(ctx context.Context, in *FizzBuzzRequest, opts ...grpc.CallOption) (*FizzBuzzResponse, error) {
	out := new(FizzBuzzResponse)
	err := c.cc.Invoke(ctx, "/play.Playgrounds/FizzBuzz", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playgroundsClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, "/play.Playgrounds/Stats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playgroundsClient) Morse(ctx context.Context, in *CodeInput, opts ...grpc.CallOption) (*CodeOutput, error) {
	out := new(CodeOutput)
	err := c.cc.Invoke(ctx, "/play.Playgrounds/Morse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playgroundsClient) Josephus(ctx context.Context, in *JosephusInput, opts ...grpc.CallOption) (*JosephusOutput, error) {
	out := new(JosephusOutput)
	err := c.cc.Invoke(ctx, "/play.Playgrounds/Josephus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaygroundsServer is the server API for Playgrounds service.
type PlaygroundsServer interface {
	FizzBuzz(context.Context, *FizzBuzzRequest) (*FizzBuzzResponse, error)
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	Morse(context.Context, *CodeInput) (*CodeOutput, error)
	Josephus(context.Context, *JosephusInput) (*JosephusOutput, error)
}

func RegisterPlaygroundsServer(s *grpc.Server, srv PlaygroundsServer) {
	s.RegisterService(&_Playgrounds_serviceDesc, srv)
}

func _Playgrounds_FizzBuzz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FizzBuzzRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaygroundsServer).FizzBuzz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/play.Playgrounds/FizzBuzz",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaygroundsServer).FizzBuzz(ctx, req.(*FizzBuzzRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Playgrounds_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaygroundsServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/play.Playgrounds/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaygroundsServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Playgrounds_Morse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CodeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaygroundsServer).Morse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/play.Playgrounds/Morse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaygroundsServer).Morse(ctx, req.(*CodeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Playgrounds_Josephus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JosephusInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaygroundsServer).Josephus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/play.Playgrounds/Josephus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaygroundsServer).Josephus(ctx, req.(*JosephusInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Playgrounds_serviceDesc = grpc.ServiceDesc{
	ServiceName: "play.Playgrounds",
	HandlerType: (*PlaygroundsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FizzBuzz",
			Handler:    _Playgrounds_FizzBuzz_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _Playgrounds_Stats_Handler,
		},
		{
			MethodName: "Morse",
			Handler:    _Playgrounds_Morse_Handler,
		},
		{
			MethodName: "Josephus",
			Handler:    _Playgrounds_Josephus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
